### ISSUE TITLE
remove line length limits

### ISSUE THREAD

**Issue by nlf** [npm/lint#2]
pros:
- avoids having to break up long lines, which is sometimes awkward (especially when the line is only very slightly over the limit)
- line length is not auto-fix friendly, so it requires manual intervention when the rule is broken

cons:
- potentially more awkward appearance of lines when the editor does the wrapping for you
- harder to say no to PRs where an excessively long line gets added

alternatives:
- raise the limit instead of removing it

**Comment by isaacs** [comment]
Could we just bump up the max-len to 90?  The other con is that it makes it harder to say no to PRs where an excessively long line gets added.

The other downside of this rule is that it's not auto-fix friendly.  If we remove it, and just try to be reasonable, I'm fine.  Personally, I try to keep code lines around 60 chars anyway, because font sizes.

**Comment by nlf** [comment]
i would definitely be open to choosing a longer limit instead, but the added fact that it's not auto fix friendly does make me lean toward removing it entirely
